Why are vectors needed?
Vectors are needed so that words can be converted to numbers that computer understands


B-o-W = Bag of Words

TF-IDF = Term Frequency - Inverse Document Frequency


vb. TF

"I love Python"  => doc1
"I love coding for life" => doc2
"I hate bugs" => doc3


            Doc1    Doc2    Doc3
I           1       1       1
love        1       1       0
coding       ..  
life    ...
learning       ...
hate    ...
bugs    ....

            3       5       3
            


word "I"  is IDF = log(3/3) = 0
word "python" is IDF = log(3/1) = 1.1

word "love" is IDF = log(3/2) = 0.18



TF-IDF = TF x IDF  



            Doc1    Doc2    Doc3
I           o       0       0
love        0.18     0.18       0
coding       ..  
life    ...
learning       ...
hate    ...
bugs    ....




In [1]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Apple is looking at buying U.K. startup for $1 billion"

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ent.label_)

Apple ORG
U.K. GPE
$1 billion MONEY


Install scikit-learn with the following code:
pip install scikit-learn

This is a Python library for Machine Learning.
It provides ready-to-use tools to:

-Train machine learning models
-Process and transform data
-Evaluate performance
-Do tasks like classification, clustering, and text vectorization




In [13]:
# Demonstration of Bag of Words (BoW)

from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
documents = [
    "I love Python.",
    "I love coding",
    "I hate bugs"
]

# Create the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Print the feature names
print(vectorizer.get_feature_names_out())

# Convert the result to an array and print it
print(X.toarray())

#it doesnt take words like I, the, and, is into account. These are called stop words and are usually filtered out in text processing tasks.

# e.g. I eat chicken = chicken eat I



['bugs' 'coding' 'hate' 'love' 'python']
[[0 0 0 1 1]
 [0 1 0 1 0]
 [1 0 1 0 0]]


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample documents
documents = [
    "I love Python.",
    "I love coding.",
    "I hate bugs"
]


# Create the TfidfVectorizer
vectorizer = TfidfVectorizer()
# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Print the feature names
print(vectorizer.get_feature_names_out())
# Convert the result to an array and print it
print(X.toarray())

['bugs' 'coding' 'hate' 'love' 'python']
[[0.         0.         0.         0.60534851 0.79596054]
 [0.         0.79596054 0.         0.60534851 0.        ]
 [0.70710678 0.         0.70710678 0.         0.        ]]


Vector transformation

- Normalisatie


In [ ]:
from sklearn.preprocessing import Normalizer
import numpy as np

x = np.array([[0, 3, 4],
              [1, 3, 9]])

normalizer = Normalizer()

X_normalized = normalizer.fit_transform(x)

print(X_normalized)

#This is to normilize the doc vectors so that they have a length of 1.
# This is often done to ensure that the vectors are comparable in terms of direction rather than magnitude,
# which can be important in various machine learning and information retrieval tasks.




[[0.         0.6        0.8       ]
 [0.10482848 0.31448545 0.94345635]]


In [18]:
print ( 0**2 + 0.6**2 + 0.8**2 ) # = 1

1.0


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import Normalizer
import numpy as np

# Voorbeeldteksten
texts = [
    "I love Python",
    "I love coding",
    "I hate bugs"
]

# Stap 1: TF-IDF vectoren maken
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

print("Feature names:", vectorizer.get_feature_names_out())
print("\nTF-IDF matrix (zonder normalisatie):")
print(X.toarray())

# Stap 2: Normaliseren
normalizer = Normalizer()
X_normalized = normalizer.fit_transform(X.toarray())

print("\nNa normalisatie:")
print(X_normalized)


Feature names: ['bugs' 'coding' 'hate' 'love' 'python']

TF-IDF matrix (zonder normalisatie):
[[0.         0.         0.         0.60534851 0.79596054]
 [0.         0.79596054 0.         0.60534851 0.        ]
 [0.70710678 0.         0.70710678 0.         0.        ]]

Na normalisatie:
[[0.         0.         0.         0.60534851 0.79596054]
 [0.         0.79596054 0.         0.60534851 0.        ]
 [0.70710678 0.         0.70710678 0.         0.        ]]


In [ ]:
Cosine similarity = (A . B) / (||A|| ||B||)

# A . B is the dot product of A and B
# ||A|| is the magnitude (length) of vector A
# ||B|| is the magnitude (length) of vector B
# Cosine similarity measures the cosine of the angle between two non-zero vectors in an inner product space.
# It is a measure of similarity between two vectors that considers their direction rather than their magnitude.
# The cosine similarity is particularly useful in high-dimensional positive spaces,
# such as text analysis, where the magnitude of the vectors may be less informative than their orientation




In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Voorbeeldteksten
texts = [
    "I love left and above. I love NLP and machine learning",
    "I love right and above. I love NLP and machine learning",
    "I love bugs"
]   




# Stap 1: TF-IDF vectoren maken
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

#words matrix
words = vectorizer.get_feature_names_out()
print("Feature names:", words)

cos_sim = cosine_similarity(X)
df = pd.DataFrame(cos_sim, columns=[f'Doc{i+1}' for i in range(len(texts))], index=[f'Doc{i+1}' for i in range(len(texts))])
print("\nCosine Similarity Matrix:")
print(df)


Feature names: ['above' 'and' 'bugs' 'learning' 'left' 'love' 'machine' 'nlp' 'right']

Cosine Similarity Matrix:
          Doc1      Doc2      Doc3
Doc1  1.000000  0.857601  0.226682
Doc2  0.857601  1.000000  0.226682
Doc3  0.226682  0.226682  1.000000


Applying n-grams and other preprocessing techniques


What are n-grams?
Sequence of n consecutive words from a text


e.g

"I love vs code"


n = 1 , unigram, [I, love, vs, code]

n = 2, bigram,   [I love, Love vs, vs code]

n = 3, trigram,  [I love vs,  love vs code]


Why is this usefull?
Because the meaning of something is very clear after bringing the words together




"not good"

unigram = not , good
bigram = not good



In [39]:
from sklearn.feature_extraction.text import CountVectorizer

texts = [
    "I love machine learning",
    "machine learning is fun",
    "I love deep learning"
]

#Unigrams (1 word per feature)
vectorizer_uni = CountVectorizer(ngram_range=(1,1))

X_uni = vectorizer_uni.fit_transform(texts)
print("Unigrams Feature names:", vectorizer_uni.get_feature_names_out())
print("Unigrams Matrix:\n", X_uni.toarray())

Unigrams Feature names: ['deep' 'fun' 'is' 'learning' 'love' 'machine']
Unigrams Matrix:
 [[0 0 0 1 1 1]
 [0 1 1 1 0 1]
 [1 0 0 1 1 0]]


In [40]:
#bi-grams (2 words per feature)
vectorizer_bi = CountVectorizer(ngram_range=(2,2))
X_bi = vectorizer_bi.fit_transform(texts)
print("\nBigrams Feature names:", vectorizer_bi.get_feature_names_out())
print("Bigrams Matrix:\n", X_bi.toarray())


Bigrams Feature names: ['deep learning' 'is fun' 'learning is' 'love deep' 'love machine'
 'machine learning']
Bigrams Matrix:
 [[0 0 0 0 1 1]
 [0 1 1 0 0 1]
 [1 0 0 1 0 0]]


In [45]:
#tri-grams (3 words per feature)
vectorizer_tri = CountVectorizer(ngram_range=(1,2))
X_tri = vectorizer_tri.fit_transform(texts)
print("\nBigrams Feature names:", vectorizer_tri.get_feature_names_out())
print("Trigrams Matrix:\n", X_tri.toarray())


Bigrams Feature names: ['deep' 'deep learning' 'fun' 'is' 'is fun' 'learning' 'learning is'
 'love' 'love deep' 'love machine' 'machine' 'machine learning']
Trigrams Matrix:
 [[0 0 0 0 0 1 0 1 0 1 1 1]
 [0 0 1 1 1 1 1 0 0 0 1 1]
 [1 1 0 0 0 1 0 1 1 0 0 0]]


Preprocessing
Voordat we tekst vectoriseren, moeten we die opschonen

Lowercasing
tekens weghalen vb. kommas, punten, !

stopwoorden weglaten

lemmatization ->  woord naar basisvorm brengen  "running" -. "run"

In [47]:
import re #regular expressions
#regular expressions are expressions that define search patterns for strings.

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emill\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
texts = [
    "I am LOVING machine-learning!!",
    "Machine learning is amazing, and I love it.",
    "I loved deep learning in Python."
]

In [58]:
# step 1 cleaning text
def preprocess(text):
    # Lowercasing
    text = text.lower()
    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

print(preprocess(texts[0]))


#step 2 verctorization with bi-grams and tri-grams

vectorizer_bi = CountVectorizer(ngram_range=(2,2))
X_bi = vectorizer_bi.fit_transform(texts)
print("\nBigrams Feature names:", vectorizer_bi.get_feature_names_out())
print("Bigrams Matrix:\n", X_bi.toarray())

loving machinelearning

Bigrams Feature names: ['am loving' 'amazing and' 'and love' 'deep learning' 'in python'
 'is amazing' 'learning in' 'learning is' 'love it' 'loved deep'
 'loving machine' 'machine learning']
Bigrams Matrix:
 [[1 0 0 0 0 0 0 0 0 0 1 1]
 [0 1 1 0 0 1 0 1 1 0 0 1]
 [0 0 0 1 1 0 1 0 0 1 0 0]]


preprocessing, TF-IDF, n-grams en cosine similarity.

Hier is een complete demo die je zo in je college kunt laten zie

In [59]:
import re
from nltk.corpus import stopwords
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Download stopwords
nltk.download('stopwords')

# Step 0: Sample texts
texts = [
    "I am LOVING machine-learning!!",
    "Machine learning is amazing, and I love it.",
    "I loved deep learning in Python."
]

# Step 1: Preprocessing function
def preprocess(text):
    # Lowercasing
    text = text.lower()
    # Remove punctuation and special characters
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

# Apply preprocessing to all texts
cleaned_texts = [preprocess(t) for t in texts]
print("Cleaned texts:\n", cleaned_texts, "\n")

# Step 2: TF-IDF with n-grams (unigrams + bigrams)
vectorizer = TfidfVectorizer(
    stop_words=stopwords.words('english'),  # remove stopwords again just to be sure
    ngram_range=(1, 2)                      # unigrams + bigrams
)
X = vectorizer.fit_transform(cleaned_texts)

# Print features (words + n-grams)
print("TF-IDF Features (unigrams + bigrams):")
print(vectorizer.get_feature_names_out(), "\n")

# Step 3: TF-IDF matrix
print("TF-IDF Matrix:")
print(X.toarray(), "\n")

# Step 4: Cosine similarity between documents
cos_sim = cosine_similarity(X)
df = pd.DataFrame(cos_sim, index=cleaned_texts, columns=cleaned_texts)
print("Cosine Similarity between documents:")
print(df.round(3))


Cleaned texts:
 ['loving machinelearning', 'machine learning amazing love', 'loved deep learning python'] 

TF-IDF Features (unigrams + bigrams):
['amazing' 'amazing love' 'deep' 'deep learning' 'learning'
 'learning amazing' 'learning python' 'love' 'loved' 'loved deep' 'loving'
 'loving machinelearning' 'machine' 'machine learning' 'machinelearning'
 'python'] 

TF-IDF Matrix:
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.57735027 0.57735027
  0.         0.         0.57735027 0.        ]
 [0.38988801 0.38988801 0.         0.         0.29651988 0.38988801
  0.         0.38988801 0.         0.         0.         0.
  0.38988801 0.38988801 0.         0.        ]
 [0.         0.         0.38988801 0.38988801 0.29651988 0.
  0.38988801 0.         0.38988801 0.38988801 0.         0.
  0.         0.         0.         0.38988801]] 

Cosine Similarity between documents:
                               loving machinelearning  \
lovi

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emill\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
